// Code generated by Slice Machine. DO NOT EDIT.

import Carousel from "./Carousel/index.svelte";
import Faqs from "./Faqs/index.svelte";
import Html from "./Html/index.svelte";
import Link from "./Link/index.svelte";
import LinkList from "./LinkList/index.svelte";
import Marquee from "./Marquee/index.svelte";
import Media from "./Media/index.svelte";
import Richtext from "./Richtext/index.svelte";
import SectionGroup from "./SectionGroup/index.svelte";

export const components = {
  carousel: Carousel,
  faqs: Faqs,
  html: Html,
  link: Link,
  link_list: LinkList,
  marquee: Marquee,
  media: Media,
  richtext: Richtext,
  section_group: SectionGroup,
};
