// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice =
  | CarouselSlice
  | FaqsSlice
  | MarqueeSlice
  | HtmlSlice
  | SectionGroupSlice
  | RichtextSlice
  | MediaSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"category">;

  /**
   * Content field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Secondary
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

/**
 * Content for Article Category documents
 */
interface CategoryDocumentData {
  /**
   * Title field in *Article Category*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Article Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | SectionGroupSlice
  | MediaSlice
  | RichtextSlice
  | FaqsSlice
  | MarqueeSlice
  | HtmlSlice
  | CarouselSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type NavigationSettingsDocumentDataSlicesHeaderSlice =
  | LinkSlice
  | LinkListSlice;

type NavigationSettingsDocumentDataSlicesHeaderUtilitySlice =
  | LinkSlice
  | LinkListSlice;

type NavigationSettingsDocumentDataSlicesFooterSlice =
  | LinkSlice
  | LinkListSlice;

type NavigationSettingsDocumentDataSlicesFooterUtilitySlice = LinkSlice;

/**
 * Content for Navigation Settings documents
 */
interface NavigationSettingsDocumentData {
  /**
   * Slice Zone field in *Navigation Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_settings.slices_header[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices_header: prismic.SliceZone<NavigationSettingsDocumentDataSlicesHeaderSlice>
  /**
   * Slice Zone field in *Navigation Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_settings.slices_header_utility[]
   * - **Tab**: Header ~ Utility
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices_header_utility: prismic.SliceZone<NavigationSettingsDocumentDataSlicesHeaderUtilitySlice>
  /**
   * Slice Zone field in *Navigation Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_settings.slices_footer[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices_footer: prismic.SliceZone<NavigationSettingsDocumentDataSlicesFooterSlice>
  /**
   * Slice Zone field in *Navigation Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_settings.slices_footer_utility[]
   * - **Tab**: Footer ~ Utility
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices_footer_utility: prismic.SliceZone<NavigationSettingsDocumentDataSlicesFooterUtilitySlice>;
}

/**
 * Navigation Settings document from Prismic
 *
 * - **API ID**: `navigation_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationSettingsDocumentData>,
    "navigation_settings",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | SectionGroupSlice
  | MediaSlice
  | RichtextSlice
  | FaqsSlice
  | MarqueeSlice
  | HtmlSlice
  | CarouselSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Parent Page field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent_page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent_page: prismic.ContentRelationshipField<"page">;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>
  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SectionDocumentDataSlicesSlice =
  | MediaSlice
  | RichtextSlice
  | FaqsSlice
  | MarqueeSlice
  | HtmlSlice;

/**
 * Content for Page Section documents
 */
interface SectionDocumentData {
  /**
   * Section Label field in *Page Section*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: section.section_label
   * - **Tab**: Section Builder
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_label: prismic.TitleField;

  /**
   * Slice Zone field in *Page Section*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: section.slices[]
   * - **Tab**: Section Builder
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SectionDocumentDataSlicesSlice>;
}

/**
 * Page Section document from Prismic
 *
 * - **API ID**: `section`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SectionDocumentData>,
    "section",
    Lang
  >;

/**
 * Content for Website Settings documents
 */
interface SettingsDocumentData {
  /**
   * Favicon field in *Website Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.favicon
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  favicon: prismic.ImageField<never>;

  /**
   * Alternative Landing Page field in *Website Settings*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.alternative_landing_page
   * - **Tab**: Settings
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  alternative_landing_page: prismic.ContentRelationshipField<"page">
  /**
   * GA Measurement ID field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.ga_measurement_id
   * - **Tab**: Analytics
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  ga_measurement_id: prismic.KeyTextField;

  /**
   * Facebook App ID field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.facebook_app_id
   * - **Tab**: Analytics
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebook_app_id: prismic.KeyTextField
  /**
   * Facebook URL field in *Website Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.facebook_url
   * - **Tab**: Social Media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  facebook_url: prismic.LinkField;

  /**
   * Instagram URL field in *Website Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram_url
   * - **Tab**: Social Media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram_url: prismic.LinkField;

  /**
   * Twitter (X) URL field in *Website Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.twitter_url
   * - **Tab**: Social Media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter_url: prismic.LinkField;

  /**
   * TikTok URL field in *Website Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.tiktok_url
   * - **Tab**: Social Media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  tiktok_url: prismic.LinkField;

  /**
   * YouTube URL field in *Website Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.youtube_url
   * - **Tab**: Social Media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  youtube_url: prismic.LinkField;

  /**
   * LinkedIn URL field in *Website Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.linkedin_url
   * - **Tab**: Social Media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin_url: prismic.LinkField
  /**
   * Rounded Corners (Components) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_inner_base
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */;
  border_radius_inner_base: prismic.NumberField;

  /**
   * Rounded Corners (Components ~ Tablet) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_inner_tb
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  border_radius_inner_tb: prismic.NumberField;

  /**
   * Rounded Corners (Components ~ Desktop) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_inner_dk
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  border_radius_inner_dk: prismic.NumberField;

  /**
   * Rounded Corners (Inputs) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_input_base
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  border_radius_input_base: prismic.NumberField;

  /**
   * Rounded Corners (Inputs ~ Tablet) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_input_tb
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  border_radius_input_tb: prismic.NumberField;

  /**
   * Rounded Corners (Inputs ~ Desktop) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_input_dk
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  border_radius_input_dk: prismic.NumberField;

  /**
   * Rounded Corners (Sections) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_outer_base
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  border_radius_outer_base: prismic.NumberField;

  /**
   * Rounded Corners (Sections ~ Tablet) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_outer_tb
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  border_radius_outer_tb: prismic.NumberField;

  /**
   * Rounded Corners (Sections ~ Desktop) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.border_radius_outer_dk
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  border_radius_outer_dk: prismic.NumberField;

  /**
   * Gap (Content) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.content_gap_base
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_gap_base: prismic.NumberField;

  /**
   * Gap (Content ~ Tablet) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.content_gap_tb
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_gap_tb: prismic.NumberField;

  /**
   * Gap (Content ~ Desktop) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.content_gap_dk
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_gap_dk: prismic.NumberField;

  /**
   * Gutter (Content) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.content_gutter_base
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_gutter_base: prismic.NumberField;

  /**
   * Gutter (Content ~ Tablet) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.content_gutter_tb
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_gutter_tb: prismic.NumberField;

  /**
   * Gutter (Content ~ Desktop) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.content_gutter_dk
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_gutter_dk: prismic.NumberField;

  /**
   * Gap (Grid) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.grid_gap_base
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  grid_gap_base: prismic.NumberField;

  /**
   * Gap (Grid ~ Tablet) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.grid_gap_tb
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  grid_gap_tb: prismic.NumberField;

  /**
   * Gap (Grid ~ Desktop) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.grid_gap_dk
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  grid_gap_dk: prismic.NumberField;

  /**
   * Gutter (Section) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_gutter_base
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  site_gutter_base: prismic.NumberField;

  /**
   * Gutter (Section ~ Tablet) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_gutter_tb
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  site_gutter_tb: prismic.NumberField;

  /**
   * Gutter (Section ~ Desktop) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_gutter_dk
   * - **Tab**: Layout
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  site_gutter_dk: prismic.NumberField
  /**
   * Max Width (Buttons) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.button_max_width_base
   * - **Tab**: Buttons
   * - **Documentation**: https://prismic.io/docs/field#number
   */;
  button_max_width_base: prismic.NumberField;

  /**
   * Max Width (Buttons ~ Tablet) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.button_max_width_tb
   * - **Tab**: Buttons
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  button_max_width_tb: prismic.NumberField;

  /**
   * Max Width (Buttons ~ Desktop) field in *Website Settings*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.button_max_width_dk
   * - **Tab**: Buttons
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  button_max_width_dk: prismic.NumberField
  /**
   * Site Title field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.title
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  title: prismic.KeyTextField;

  /**
   * Site Description field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.description
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Theme Background field in *Website Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.theme_background
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_background: prismic.ColorField;

  /**
   * Theme Accent field in *Website Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.theme_accent
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_accent: prismic.ColorField;

  /**
   * Theme Font field in *Website Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.theme_font
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_font: prismic.ColorField;

  /**
   * Theme Button Background field in *Website Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.theme_button_background
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_button_background: prismic.ColorField;

  /**
   * Theme Button Accent field in *Website Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.theme_button_accent
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_button_accent: prismic.ColorField;

  /**
   * Theme Button Font field in *Website Settings*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.theme_button_font
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  theme_button_font: prismic.ColorField;

  /**
   * Google Font - Headlines field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.google_font_headlines
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_font_headlines: prismic.KeyTextField;

  /**
   * Google Font - Headlines Alt field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.google_font_headlines_alt
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_font_headlines_alt: prismic.KeyTextField;

  /**
   * Google Font - Body field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.google_font_body
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_font_body: prismic.KeyTextField;

  /**
   * Google Font - Body Alt field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.google_font_body_alt
   * - **Tab**: Branding
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  google_font_body_alt: prismic.KeyTextField
  /**
   * Organization Name field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.organization_name
   * - **Tab**: Organization
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  organization_name: prismic.KeyTextField;

  /**
   * Organization Legal Name field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.organization_legal_name
   * - **Tab**: Organization
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  organization_legal_name: prismic.KeyTextField;

  /**
   * Organization Description field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.organization_description
   * - **Tab**: Organization
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  organization_description: prismic.KeyTextField;

  /**
   * Organization Logo field in *Website Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.organization_logo
   * - **Tab**: Organization
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  organization_logo: prismic.ImageField<never>;

  /**
   * Organization URL field in *Website Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.organization_url
   * - **Tab**: Organization
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  organization_url: prismic.LinkField;

  /**
   * Organization Email field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.organization_email
   * - **Tab**: Organization
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  organization_email: prismic.KeyTextField;

  /**
   * Organization Phone field in *Website Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.organization_phone
   * - **Tab**: Organization
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  organization_phone: prismic.KeyTextField;
}

/**
 * Website Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | CategoryDocument
  | HomeDocument
  | NavigationSettingsDocument
  | PageDocument
  | SectionDocument
  | SettingsDocument;

/**
 * Primary content in *Carousel → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Eyebrow field in *Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Content field in *Carousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *Carousel → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Text field in *Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Style field in *Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Primary
   * - **API ID Path**: carousel.primary.button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    | "Primary"
    | "Primary Reverse"
    | "Secondary"
    | "Secondary Reverse"
    | "Inherit"
    | "Inherit Reverse"
    | "Text",
    "filled"
  >;

  /**
   * Font Color field in *Carousel → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.content_box_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_font_color: prismic.ColorField;

  /**
   * Carousel Section Content field in *Carousel → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section: prismic.ContentRelationshipField<"section">;

  /**
   * Carousel Pages to Show field in *Carousel → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.content_pages
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_pages: prismic.NumberField;

  /**
   * Slides Per Page field in *Carousel → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.content_per_page
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_per_page: prismic.NumberField;

  /**
   * Slide Alignment field in *Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Fill
   * - **API ID Path**: carousel.primary.column_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column_alignment: prismic.SelectField<
    "Fill" | "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Fullscreen (minimum) field in *Carousel → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel.primary.column_screen
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  column_screen: prismic.BooleanField;

  /**
   * Section Padding field in *Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: carousel.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Carousel → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Carousel → Primary*
 */
export interface CarouselSliceArticleRecirculationPrimary {
  /**
   * Eyebrow field in *Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Content field in *Carousel → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *Carousel → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Text field in *Carousel → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Style field in *Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Primary
   * - **API ID Path**: carousel.primary.button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    | "Primary"
    | "Primary Reverse"
    | "Secondary"
    | "Secondary Reverse"
    | "Inherit"
    | "Inherit Reverse"
    | "Text",
    "filled"
  >;

  /**
   * Font Color field in *Carousel → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.content_box_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_font_color: prismic.ColorField;

  /**
   * Article Category field in *Carousel → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section: prismic.ContentRelationshipField<"category">;

  /**
   * Carousel Pages to Show field in *Carousel → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.content_pages
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_pages: prismic.NumberField;

  /**
   * Slides Per Page field in *Carousel → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.content_per_page
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_per_page: prismic.NumberField;

  /**
   * Slide Alignment field in *Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Fill
   * - **API ID Path**: carousel.primary.column_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column_alignment: prismic.SelectField<
    "Fill" | "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Fullscreen (minimum) field in *Carousel → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: carousel.primary.column_screen
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  column_screen: prismic.BooleanField;

  /**
   * Section Padding field in *Carousel → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: carousel.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Carousel → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * Article Recirculation variation for Carousel Slice
 *
 * - **API ID**: `articleRecirculation`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceArticleRecirculation = prismic.SharedSliceVariation<
  "articleRecirculation",
  Simplify<CarouselSliceArticleRecirculationPrimary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation =
  | CarouselSliceDefault
  | CarouselSliceArticleRecirculation;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *Faqs → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Eyebrow field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Content field in *Faqs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Content Box Text Justification field in *Faqs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: faqs.primary.content_box_text_justification
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_text_justification: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Content Box Horizontal Alignment field in *Faqs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: faqs.primary.content_box_horizontal
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_horizontal: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Content Box Vertical Alignment field in *Faqs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: faqs.primary.content_box_vertical
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_vertical: prismic.SelectField<
    "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Content Max Width (px) field in *Faqs → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Accepts values between 300 and 1600
   * - **API ID Path**: faqs.primary.content_max_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_max_width: prismic.NumberField;

  /**
   * Section Font Color field in *Faqs → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.content_box_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_font_color: prismic.ColorField;

  /**
   * Section Padding field in *Faqs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: faqs.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Faqs → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * Primary content in *Faqs → Items*
 */
export interface FaqsSliceDefaultItem {
  /**
   * FAQ Title field in *Faqs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.items[].faq_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  faq_title: prismic.RichTextField;

  /**
   * FAQ Details field in *Faqs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.items[].faq_details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  faq_details: prismic.RichTextField;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  Simplify<FaqsSliceDefaultItem>
>;

/**
 * Primary content in *Faqs → Primary*
 */
export interface FaqsSliceWithMediaPrimary {
  /**
   * Image field in *Faqs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Faqs → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField;

  /**
   * Media Fit field in *Faqs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cover
   * - **API ID Path**: faqs.primary.media_fit
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  media_fit: prismic.SelectField<"Cover" | "Contain", "filled">;

  /**
   * Eyebrow field in *Faqs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Content field in *Faqs → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Content Box Text Justification field in *Faqs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: faqs.primary.content_box_text_justification
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_text_justification: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Content Box Vertical Alignment field in *Faqs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: faqs.primary.content_box_vertical
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_vertical: prismic.SelectField<
    "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Content Box Font Color field in *Faqs → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.content_box_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_font_color: prismic.ColorField;

  /**
   * Section Padding field in *Faqs → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: faqs.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Faqs → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * Primary content in *Faqs → Items*
 */
export interface FaqsSliceWithMediaItem {
  /**
   * FAQ Title field in *Faqs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.items[].faq_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  faq_title: prismic.RichTextField;

  /**
   * FAQ Details field in *Faqs → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.items[].faq_details
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  faq_details: prismic.RichTextField;
}

/**
 * With Media variation for Faqs Slice
 *
 * - **API ID**: `with_media`
 * - **Description**: Faqs with a Media component
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSliceWithMedia = prismic.SharedSliceVariation<
  "with_media",
  Simplify<FaqsSliceWithMediaPrimary>,
  Simplify<FaqsSliceWithMediaItem>
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault | FaqsSliceWithMedia;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *Html → Primary*
 */
export interface HtmlSliceDefaultPrimary {
  /**
   * Snippet field in *Html → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Copy/Paste raw embed snippets
   * - **API ID Path**: html.primary.snippet
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  snippet: prismic.RichTextField;

  /**
   * Content Max Width (px) field in *Html → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Accepts values between 300 and 1600
   * - **API ID Path**: html.primary.content_max_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_max_width: prismic.NumberField;

  /**
   * Section Padding field in *Html → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: html.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Html → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: html.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * Default variation for Html Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HtmlSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HtmlSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Html*
 */
type HtmlSliceVariation = HtmlSliceDefault;

/**
 * Html Shared Slice
 *
 * - **API ID**: `html`
 * - **Description**: Html
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HtmlSlice = prismic.SharedSlice<"html", HtmlSliceVariation>;

/**
 * Primary content in *Link → Primary*
 */
export interface LinkSliceDefaultPrimary {
  /**
   * Link field in *Link → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *Link → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link Style field in *Link → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Text
   * - **API ID Path**: link.primary.link_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  link_style: prismic.SelectField<"Text" | "Button", "filled">;
}

/**
 * Default variation for Link Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Link*
 */
type LinkSliceVariation = LinkSliceDefault;

/**
 * Link Shared Slice
 *
 * - **API ID**: `link`
 * - **Description**: Link
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSlice = prismic.SharedSlice<"link", LinkSliceVariation>;

/**
 * Primary content in *LinkList → Primary*
 */
export interface LinkListSliceDefaultPrimary {
  /**
   * Menu Text field in *LinkList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.primary.menu_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_text: prismic.KeyTextField;

  /**
   * Link field in *LinkList → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *LinkList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Expand on Mobile field in *LinkList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: link_list.primary.link_open
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  link_open: prismic.BooleanField;
}

/**
 * Primary content in *LinkList → Items*
 */
export interface LinkListSliceDefaultItem {
  /**
   * Link field in *LinkList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *LinkList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.items[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;
}

/**
 * Default variation for LinkList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkListSliceDefaultPrimary>,
  Simplify<LinkListSliceDefaultItem>
>;

/**
 * Primary content in *LinkList → Primary*
 */
export interface LinkListSliceMegaMenuPrimary {
  /**
   * Menu Text field in *LinkList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.primary.menu_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  menu_text: prismic.KeyTextField;

  /**
   * Link field in *LinkList → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *LinkList → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.primary.link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Columns field in *LinkList → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.primary.columns
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  columns: prismic.NumberField;

  /**
   * Flex Content field in *LinkList → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.primary.flex_content
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  flex_content: prismic.ContentRelationshipField<"section">;

  /**
   * Flex Content Justification field in *LinkList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: link_list.primary.flex_content_justification
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  flex_content_justification: prismic.BooleanField;

  /**
   * Flex Content within Drawer on Mobile field in *LinkList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: link_list.primary.flex_inside
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  flex_inside: prismic.BooleanField;

  /**
   * Hide Flex Content on Mobile field in *LinkList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: link_list.primary.flex_hide
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  flex_hide: prismic.BooleanField;

  /**
   * Expand on Mobile field in *LinkList → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: link_list.primary.link_open
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  link_open: prismic.BooleanField;
}

/**
 * Primary content in *LinkList → Items*
 */
export interface LinkListSliceMegaMenuItem {
  /**
   * Link field in *LinkList → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link Text field in *LinkList → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.items[].link_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField;

  /**
   * Link Column field in *LinkList → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: link_list.items[].link_column
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  link_column: prismic.NumberField;
}

/**
 * Mega Menu variation for LinkList Slice
 *
 * - **API ID**: `megaMenu`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkListSliceMegaMenu = prismic.SharedSliceVariation<
  "megaMenu",
  Simplify<LinkListSliceMegaMenuPrimary>,
  Simplify<LinkListSliceMegaMenuItem>
>;

/**
 * Slice variation for *LinkList*
 */
type LinkListSliceVariation = LinkListSliceDefault | LinkListSliceMegaMenu;

/**
 * LinkList Shared Slice
 *
 * - **API ID**: `link_list`
 * - **Description**: LinkList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkListSlice = prismic.SharedSlice<
  "link_list",
  LinkListSliceVariation
>;

/**
 * Primary content in *Marquee → Primary*
 */
export interface MarqueeSliceDefaultPrimary {
  /**
   * Marquee Pause on Hover field in *Marquee → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: marquee.primary.marquee_pause_on_hover
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  marquee_pause_on_hover: prismic.BooleanField;

  /**
   * Marquee Speed field in *Marquee → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Enter a number below 100
   * - **API ID Path**: marquee.primary.marquee_speed
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  marquee_speed: prismic.NumberField;

  /**
   * Section Font Color field in *Marquee → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.primary.content_box_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_font_color: prismic.ColorField;

  /**
   * Section Padding field in *Marquee → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: marquee.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Marquee → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;

  /**
   * Content Vertical Padding field in *Marquee → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: marquee.primary.content_vertical_padding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  content_vertical_padding: prismic.BooleanField;
}

/**
 * Primary content in *Marquee → Items*
 */
export interface MarqueeSliceDefaultItem {
  /**
   * Marquee Row field in *Marquee → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.items[].marquee_row
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  marquee_row: prismic.RichTextField;

  /**
   * Marquee Row Background Color field in *Marquee → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.items[].marquee_row_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  marquee_row_background_color: prismic.ColorField;

  /**
   * Marquee Row Font Color field in *Marquee → Items*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.items[].marquee_row_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  marquee_row_font_color: prismic.ColorField;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceDefaultPrimary>,
  Simplify<MarqueeSliceDefaultItem>
>;

/**
 * Primary content in *Marquee → Primary*
 */
export interface MarqueeSliceImagesPrimary {
  /**
   * Marquee Pause on Hover field in *Marquee → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: marquee.primary.marquee_pause_on_hover
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  marquee_pause_on_hover: prismic.BooleanField;

  /**
   * Marquee Direction field in *Marquee → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: marquee.primary.marquee_direction
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  marquee_direction: prismic.BooleanField;

  /**
   * Marquee Speed field in *Marquee → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Enter a number below 100
   * - **API ID Path**: marquee.primary.marquee_speed
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  marquee_speed: prismic.NumberField;

  /**
   * Marquee Max Height field in *Marquee → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.primary.marquee_max_height
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  marquee_max_height: prismic.NumberField;

  /**
   * Image Alignment field in *Marquee → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Fill
   * - **API ID Path**: marquee.primary.column_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column_alignment: prismic.SelectField<
    "Fill" | "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Section Padding field in *Marquee → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: marquee.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Marquee → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;

  /**
   * Content Vertical Padding field in *Marquee → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: marquee.primary.content_vertical_padding
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  content_vertical_padding: prismic.BooleanField;
}

/**
 * Primary content in *Marquee → Items*
 */
export interface MarqueeSliceImagesItem {
  /**
   * Marquee Image field in *Marquee → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.items[].marquee_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  marquee_image: prismic.ImageField<never>;
}

/**
 * Images variation for Marquee Slice
 *
 * - **API ID**: `images`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSliceImages = prismic.SharedSliceVariation<
  "images",
  Simplify<MarqueeSliceImagesPrimary>,
  Simplify<MarqueeSliceImagesItem>
>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeSliceVariation = MarqueeSliceDefault | MarqueeSliceImages;

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: Marquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSlice = prismic.SharedSlice<
  "marquee",
  MarqueeSliceVariation
>;

/**
 * Primary content in *Media → Primary*
 */
export interface MediaSliceDefaultPrimary {
  /**
   * Image field in *Media → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Media → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField;

  /**
   * Video Playback field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Autoplay
   * - **API ID Path**: media.primary.video_playback
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  video_playback: prismic.SelectField<
    "Autoplay" | "Loop" | "Autoplay + Loop" | "None",
    "filled"
  >;

  /**
   * Media Fit field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cover
   * - **API ID Path**: media.primary.media_fit
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  media_fit: prismic.SelectField<"Cover" | "Contain", "filled">;

  /**
   * Media Aspect Ratio field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: media.primary.media_aspect_ratio
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  media_aspect_ratio: prismic.SelectField<
    "None" | "1:1" | "4:3" | "16:9",
    "filled"
  >;

  /**
   * Media Round Corners field in *Media → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: media.primary.media_round_corners
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  media_round_corners: prismic.BooleanField;

  /**
   * Media Shadow field in *Media → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: media.primary.media_shadow
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  media_shadow: prismic.BooleanField;

  /**
   * Eyebrow field in *Media → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Content field in *Media → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *Media → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Text field in *Media → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Style field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Primary
   * - **API ID Path**: media.primary.button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    | "Primary"
    | "Primary Reverse"
    | "Secondary"
    | "Secondary Reverse"
    | "Inherit"
    | "Inherit Reverse"
    | "Text",
    "filled"
  >;

  /**
   * Content Box Text Justification field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: media.primary.content_box_text_justification
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_text_justification: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Content Box Horizontal Alignment field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: media.primary.content_box_horizontal
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_horizontal: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Content Box Vertical Alignment field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: media.primary.content_box_vertical
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_vertical: prismic.SelectField<
    "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Content Box Font Color field in *Media → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.content_box_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_font_color: prismic.ColorField;

  /**
   * Content Box Background Color field in *Media → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.content_box_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_background_color: prismic.ColorField;

  /**
   * Content Break on Mobile field in *Media → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: media.primary.content_break_mobile
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  content_break_mobile: prismic.BooleanField;

  /**
   * Section Padding field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: media.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Media → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * With Content & CTA variation for Media Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Media → Primary*
 */
export interface MediaSliceMediaSplitPrimary {
  /**
   * Image field in *Media → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *Media → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField;

  /**
   * Media Fit field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cover
   * - **API ID Path**: media.primary.media_fit
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  media_fit: prismic.SelectField<"Cover" | "Contain", "filled">;

  /**
   * Media Aspect Ratio field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: media.primary.media_aspect_ratio
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  media_aspect_ratio: prismic.SelectField<
    "None" | "1:1" | "4:3" | "16:9",
    "filled"
  >;

  /**
   * Media Round Corners field in *Media → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: media.primary.media_round_corners
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  media_round_corners: prismic.BooleanField;

  /**
   * Eyebrow field in *Media → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Content field in *Media → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *Media → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Text field in *Media → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Style field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Primary
   * - **API ID Path**: media.primary.button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    | "Primary"
    | "Primary Reverse"
    | "Secondary"
    | "Secondary Reverse"
    | "Inherit"
    | "Inherit Reverse"
    | "Text",
    "filled"
  >;

  /**
   * Content Box Text Justification field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: media.primary.content_box_text_justification
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_text_justification: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Content Box Vertical Alignment field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: media.primary.content_box_vertical
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_vertical: prismic.SelectField<
    "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Content Box Font Color field in *Media → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.content_box_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_font_color: prismic.ColorField;

  /**
   * Force Single Column field in *Media → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: media.primary.content_break_mobile
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  content_break_mobile: prismic.BooleanField;

  /**
   * Section Desktop Layout field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Text Left
   * - **API ID Path**: media.primary.section_desktop_layout
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_desktop_layout: prismic.SelectField<
    "Image Left" | "Text Left",
    "filled"
  >;

  /**
   * Section Mobile Layout field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Image Top
   * - **API ID Path**: media.primary.section_mobile_layout
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_mobile_layout: prismic.SelectField<
    "Image Top" | "Text Top",
    "filled"
  >;

  /**
   * Section Padding field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: media.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Media → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * With Content & CTA (Split) variation for Media Slice
 *
 * - **API ID**: `media_split`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSliceMediaSplit = prismic.SharedSliceVariation<
  "media_split",
  Simplify<MediaSliceMediaSplitPrimary>,
  never
>;

/**
 * Primary content in *Media → Primary*
 */
export interface MediaSliceMediaFullscreenPrimary {
  /**
   * Image (Landscape) field in *Media → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Image (Portrait) field in *Media → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.image_portrait
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_portrait: prismic.ImageField<never>;

  /**
   * Video (Landscape) field in *Media → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField;

  /**
   * Video (Portrait) field in *Media → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.video_portrait
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_portrait: prismic.LinkField;

  /**
   * Media Fit field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Cover
   * - **API ID Path**: media.primary.media_fit
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  media_fit: prismic.SelectField<"Cover" | "Contain", "filled">;

  /**
   * Media Aspect Ratio field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: media.primary.media_aspect_ratio
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  media_aspect_ratio: prismic.SelectField<
    "None" | "1:1" | "4:3" | "16:9",
    "filled"
  >;

  /**
   * Media Round Corners field in *Media → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: media.primary.media_round_corners
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  media_round_corners: prismic.BooleanField;

  /**
   * Force Portrait on Mobile field in *Media → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: media.primary.force_portrait_mobile
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  force_portrait_mobile: prismic.BooleanField;

  /**
   * Section Padding field in *Media → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: media.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Media → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: media.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * Fullscreen Media Only variation for Media Slice
 *
 * - **API ID**: `media_fullscreen`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSliceMediaFullscreen = prismic.SharedSliceVariation<
  "media_fullscreen",
  Simplify<MediaSliceMediaFullscreenPrimary>,
  never
>;

/**
 * Slice variation for *Media*
 */
type MediaSliceVariation =
  | MediaSliceDefault
  | MediaSliceMediaSplit
  | MediaSliceMediaFullscreen;

/**
 * Media Shared Slice
 *
 * - **API ID**: `media`
 * - **Description**: Media and/or Content
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSlice = prismic.SharedSlice<"media", MediaSliceVariation>;

/**
 * Primary content in *Richtext → Primary*
 */
export interface RichtextSliceDefaultPrimary {
  /**
   * Eyebrow field in *Richtext → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: richtext.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Content field in *Richtext → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: richtext.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Link field in *Richtext → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: richtext.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Text field in *Richtext → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: richtext.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Style field in *Richtext → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Primary
   * - **API ID Path**: richtext.primary.button_style
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_style: prismic.SelectField<
    | "Primary"
    | "Primary Reverse"
    | "Secondary"
    | "Secondary Reverse"
    | "Inherit"
    | "Inherit Reverse"
    | "Text",
    "filled"
  >;

  /**
   * Content Box Text Justification field in *Richtext → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: richtext.primary.content_box_text_justification
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_text_justification: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Content Box Horizontal Alignment field in *Richtext → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: richtext.primary.content_box_horizontal
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_horizontal: prismic.SelectField<
    "Left" | "Center" | "Right",
    "filled"
  >;

  /**
   * Content Box Vertical Alignment field in *Richtext → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Center
   * - **API ID Path**: richtext.primary.content_box_vertical
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  content_box_vertical: prismic.SelectField<
    "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Content Max Width (px) field in *Richtext → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Accepts values between 300 and 1600
   * - **API ID Path**: richtext.primary.content_max_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  content_max_width: prismic.NumberField;

  /**
   * Section Font Color field in *Richtext → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: richtext.primary.content_box_font_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  content_box_font_color: prismic.ColorField;

  /**
   * Section Padding field in *Richtext → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: richtext.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *Richtext → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: richtext.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * Default variation for Richtext Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichtextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichtextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Richtext*
 */
type RichtextSliceVariation = RichtextSliceDefault;

/**
 * Richtext Shared Slice
 *
 * - **API ID**: `richtext`
 * - **Description**: Richtext
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichtextSlice = prismic.SharedSlice<
  "richtext",
  RichtextSliceVariation
>;

/**
 * Primary content in *SectionGroup → Primary*
 */
export interface SectionGroupSliceDefaultPrimary {
  /**
   * Grid Section field in *SectionGroup → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: section_group.primary.section
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  section: prismic.ContentRelationshipField<"section">;

  /**
   * Columns field in *SectionGroup → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: section_group.primary.column_count
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column_count: prismic.SelectField<"1" | "2" | "3" | "4" | "5", "filled">;

  /**
   * Column Gap field in *SectionGroup → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: section_group.primary.column_gap
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  column_gap: prismic.BooleanField;

  /**
   * Column Alignment field in *SectionGroup → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Fill
   * - **API ID Path**: section_group.primary.column_alignment
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  column_alignment: prismic.SelectField<
    "Fill" | "Top" | "Center" | "Bottom",
    "filled"
  >;

  /**
   * Fullscreen (minimum) field in *SectionGroup → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: section_group.primary.column_screen
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  column_screen: prismic.BooleanField;

  /**
   * Column Max Width (px) field in *SectionGroup → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: Accepts values between 240 and 1600
   * - **API ID Path**: section_group.primary.column_max_width
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  column_max_width: prismic.NumberField;

  /**
   * Section Padding field in *SectionGroup → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: section_group.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  section_padding: prismic.SelectField<
    | "None"
    | "Top"
    | "Top + Bottom"
    | "Bottom"
    | "Left"
    | "Left + Right"
    | "Right"
    | "No Top"
    | "No Bottom"
    | "All",
    "filled"
  >;

  /**
   * Section Background Color field in *SectionGroup → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: section_group.primary.section_background_color
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  section_background_color: prismic.ColorField;
}

/**
 * Default variation for SectionGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionGroupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionGroupSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionGroup*
 */
type SectionGroupSliceVariation = SectionGroupSliceDefault;

/**
 * SectionGroup Shared Slice
 *
 * - **API ID**: `section_group`
 * - **Description**: SectionGroup
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionGroupSlice = prismic.SharedSlice<
  "section_group",
  SectionGroupSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      CategoryDocument,
      CategoryDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavigationSettingsDocument,
      NavigationSettingsDocumentData,
      NavigationSettingsDocumentDataSlicesHeaderSlice,
      NavigationSettingsDocumentDataSlicesHeaderUtilitySlice,
      NavigationSettingsDocumentDataSlicesFooterSlice,
      NavigationSettingsDocumentDataSlicesFooterUtilitySlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SectionDocument,
      SectionDocumentData,
      SectionDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      CarouselSlice,
      CarouselSliceDefaultPrimary,
      CarouselSliceArticleRecirculationPrimary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      CarouselSliceArticleRecirculation,
      FaqsSlice,
      FaqsSliceDefaultPrimary,
      FaqsSliceDefaultItem,
      FaqsSliceWithMediaPrimary,
      FaqsSliceWithMediaItem,
      FaqsSliceVariation,
      FaqsSliceDefault,
      FaqsSliceWithMedia,
      HtmlSlice,
      HtmlSliceDefaultPrimary,
      HtmlSliceVariation,
      HtmlSliceDefault,
      LinkSlice,
      LinkSliceDefaultPrimary,
      LinkSliceVariation,
      LinkSliceDefault,
      LinkListSlice,
      LinkListSliceDefaultPrimary,
      LinkListSliceDefaultItem,
      LinkListSliceMegaMenuPrimary,
      LinkListSliceMegaMenuItem,
      LinkListSliceVariation,
      LinkListSliceDefault,
      LinkListSliceMegaMenu,
      MarqueeSlice,
      MarqueeSliceDefaultPrimary,
      MarqueeSliceDefaultItem,
      MarqueeSliceImagesPrimary,
      MarqueeSliceImagesItem,
      MarqueeSliceVariation,
      MarqueeSliceDefault,
      MarqueeSliceImages,
      MediaSlice,
      MediaSliceDefaultPrimary,
      MediaSliceMediaSplitPrimary,
      MediaSliceMediaFullscreenPrimary,
      MediaSliceVariation,
      MediaSliceDefault,
      MediaSliceMediaSplit,
      MediaSliceMediaFullscreen,
      RichtextSlice,
      RichtextSliceDefaultPrimary,
      RichtextSliceVariation,
      RichtextSliceDefault,
      SectionGroupSlice,
      SectionGroupSliceDefaultPrimary,
      SectionGroupSliceVariation,
      SectionGroupSliceDefault,
    };
  }
}
